services:
  iris:
    # get the latest version of InterSystems IRIS Community Edition
    # image: $IMAGE_IRIS_EM
    # image: $IMAGE_IRIS_CD
    # image: $IMAGE_IRIS_PREVIEW
    image: $IMAGE_IRIS
    container_name: $CONTAINER_IRIS
    hostname: $CONTAINER_IRIS
    # map the host port 1972 to the container port 1000
    ports:
      - $IRIS_MGR_PORT:1972
      - $IRIS_WEB_PORT:52773
    environment:
      - IRIS_USER=$IRIS_USER
      - IRIS_PASSWORD=$IRIS_PASSWORD
      - ISC_DATA_DIRECTORY=$IRIS_DATA_DIRECTORY # define the persistent directory for IRIS
      - TZ=Europe/Paris
      - ISC_CPF_MERGE_FILE=$ISC_CPF_MERGE_FILE # define the merge file for IRIS setup
    restart: always
    volumes:
      - ./data:/data
      - ./code:/code
      - ./IRIS:$IRIS_DATA_DIRECTORY
  